FROM ubuntu:22.04

ENV LANG=C.UTF-8
ENV LANGUAGE=C.UTF-8
ENV LC_ALL=C.UTF-8
ENV DEBIAN_FRONTEND=noninteractive
ARG AGENT_VERSION
ENV AGENT_VERSION=${AGENT_VERSION}
ARG TARGETARCH
ENV TARGETARCH=${TARGETARCH}

RUN apt update
RUN apt install -y \
    curl \
    git \
    jq \
    libicu70 \
    apt-transport-https \
    ca-certificates \
    software-properties-common \
    wget \
    apt-utils \
    unzip \
    zip
RUN apt upgrade -y

RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash

# Install Java JDK
RUN apt-get update && \
    apt-get install -y openjdk-21-jdk maven

RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /azp/

COPY ./start.sh ./
RUN chmod +x ./start.sh

RUN useradd -m -d /home/agent agent
RUN chown -R agent:agent /azp /home/agent

USER agent

ENTRYPOINT [ "./start.sh" ]
